server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # Enable discovering services from Nacos
          lower-case-service-id: true # Use lowercase service IDs
      routes:
        - id: boss_route
          uri: lb://boss-service
          predicates:
            - Path=/boss/**
        - id: basic_route
          uri: lb://basic-service
          predicates:
            - Path=/basic/**
